service-name: "minecraft-server"

logs:
  enabled: true
  otlp-endpoint: "http://localhost:4318/v1/logs"

metrics:
  enabled: true
  otlp-endpoint: "http://localhost:4318/v1/metrics"
  export-interval-seconds: 60
  types:
    tps: true
    log-count: true
    player-count: true
    entity-count: true
    loaded-chunks: true
